### ISSUE TITLE
Features / Todos

### ISSUE THREAD

**Issue by Rhyyn** [Rhyyn/my-portfolio#4]
Features or things that needs fixing : 

## Todo

- [ ] Contact / About Me Page
- [ ] Individuals Projects Pages with their description and more about technologies / issues faced
- [ ] French translation for every page
- [ ] Styling of the Home page
